### ISSUE TITLE
run.py / config uniq_id error

### ISSUE THREAD

**Issue by mickaelmonsieur** [YoannQueret/ODR-EncoderManager#9]
supervisor runs, run.py too, but port 8080 is closed. 
And I have the following error in the log:

```
Traceback (most recent call last):
  File "/home/odr/ODR-EncoderManager/run.py", line 174, in <module>
    config.initConfigurationChanged()
  File "/home/odr/ODR-EncoderManager/config/__init__.py", line 59, in initConfigurationChanged
    self.addConfigurationChanged(coder['uniq_id'])
KeyError: 'uniq_id'
```

I am using the example config.

**Comment by YoannQueret** [comment]
is run.py process can write config.json ?
Normally, when you start run.py and config.json not have uniq_id, a new uniq_id is created and config.json is updated.

**Comment by mickaelmonsieur** [comment]
yes run.py run with odr user: 

```
odr       3844  0.3  1.3  91576 27888 ?        S    16:08   0:00 /usr/bin/python3 /home/odr/ODR-EncoderManager/run.py -c config.json
```

```
root@dab:/home/odr/ODR-EncoderManager# ls -al
total 148
drwxr-xr-x 11 odr odr  4096 oct  7 16:04 .
drwxr-xr-x  7 odr odr  4096 oct  7 14:44 ..
drwxr-xr-x  3 odr odr  4096 oct  7 14:45 api
drwxr-xr-x  3 odr odr  4096 oct  7 14:45 auth
drwxr-xr-x  3 odr odr  4096 oct  7 14:45 avt
drwxr-xr-x  3 odr odr  4096 oct  7 15:37 config
-rwxrwxrwx  1 odr odr  3403 oct  7 16:08 config.json
-rw-r--r--  1 odr odr  3047 oct  7 15:50 config.json.sample
-rwxr-xr-x  1 odr odr  1068 oct  7 14:44 generate_network_config.py
-rwxr-xr-x  1 odr odr  2039 oct  7 14:44 generate_supervisor_config.py
drwxr-xr-x  8 odr odr  4096 oct  7 15:50 .git
-rw-r--r--  1 odr odr    92 oct  7 14:44 .gitignore
drwxr-xr-x  2 odr odr  4096 oct  7 14:44 lcd
-rwxr-xr-x  1 odr odr  2495 oct  7 14:44 lcd.py
-rw-r--r--  1 odr odr   674 oct  7 14:44 LICENCE
drwxr-xr-x  2 odr odr  4096 oct  7 14:44 logs
-rw-r--r--  1 odr odr 56718 oct  7 14:44 ODR-Encoder_Manager.png
-rwxr-xr-x  1 odr odr  3790 oct  7 14:44 README.md
-rwxr-xr-x  1 odr odr  8049 oct  7 14:44 run.py
drwxr-xr-x  5 odr odr  4096 oct  7 14:44 static
-rw-r--r--  1 odr odr     0 oct  7 15:53 supervisor-encoder.conf
-rw-r--r--  1 odr odr   324 oct  7 14:44 supervisor-gui.conf
-rwxr-xr-x  1 odr odr   337 oct  7 14:44 supervisor-lcd.conf
drwxr-xr-x  2 odr odr  4096 oct  7 14:44 templates
```

**Comment by CyberMixRo** [comment]
Hello,

I have similar issue, also using "next" branch, same as mickaelmonsieur :

Use configuration file config.json
Traceback (most recent call last):
  File "/home/odr/ODR-EncoderManager/run.py", line 174, in <module>
    config.initConfigurationChanged()
  File "/home/odr/ODR-EncoderManager/config/__init__.py", line 59, in initConfigurationChanged
    self.addConfigurationChanged(coder['uniq_id'])
KeyError: 'uniq_id'

I check also and config is writable
